version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload \
        "project.main:create_app('development')"
    env_file:
      - '.env'
    volumes:
      - '.:/project'
    environment:
      PYTHONUNBUFFERED: 'true'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -l info -A project.celery_app.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/project'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

volumes:
  redis: